start-at-login = true


after-startup-command = [
  'exec-and-forget sketchybar',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]
exec-on-workspace-change = [
    '/bin/bash', 
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]
###############################################################################
# Normalization settings keep your window tree neat.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

###############################################################################
# Startup and Focus Behavior
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = [
	"move-mouse window-lazy-center",
	'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
	'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',

	]
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true

###############################################################################
# Layout Settings
accordion-padding = 20
default-root-container-layout = 'tiles'

[gaps]
inner.horizontal = 0
inner.vertical   = 0
outer.left       = 0
outer.bottom     = 0
outer.top        = 0
outer.right      = 0

###############################################################################
# Keyboard Mapping
[key-mapping]
preset = 'qwerty'

###############################################################################
# Main Mode Key Bindings – Primary window management on ctrl-alt
[mode.main.binding]
    

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
# Open a new Terminal window (Cmd+N)



cmd-n = '''exec-and-forget osascript -e '
tell application "Terminal"
	do script
	activate
end tell'
'''
# workspace move
ctrl-alt-1 = 'workspace --auto-back-and-forth 1'  # Notes
ctrl-alt-2 = 'workspace --auto-back-and-forth 2'  # Terminal

#add to workspace
cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'


cmd-shift-tab = 'workspace-back-and-forth'
cmd-p = 'move-workspace-to-monitor --wrap-around next'

# Window movement using ctrl-alt arrow keys:
ctrl-alt-left  = "exec-and-forget move-window left"
ctrl-alt-right = "exec-and-forget move-window right"
ctrl-alt-up    = "exec-and-forget move-window up"
ctrl-alt-down  = "exec-and-forget move-window down"

# Focus movement using ctrl-alt-shift arrow keys:
ctrl-alt-shift-left  = 'focus --boundaries-action wrap-around-the-workspace left'
ctrl-alt-shift-right = 'focus --boundaries-action wrap-around-the-workspace right'
ctrl-alt-shift-up    = 'focus --boundaries-action wrap-around-the-workspace up'
ctrl-alt-shift-down  = 'focus --boundaries-action wrap-around-the-workspace down'

# Fullscreen toggle and moving window to next screen:
ctrl-alt-enter      = "exec-and-forget toggle-fullscreen"
ctrl-alt-cmd-right  = "exec-and-forget move-window-to-next-screen"

# Container joins (instead of split) work well with normalizations
ctrl-alt-h = 'join-with down'
ctrl-alt-v = 'join-with right'

# Allow dragging windows by toggling floating mode:
ctrl-alt-d = "exec-and-forget layout floating tiling"

# Optional layout switching commands (remain on Alt combos)
ctrl-shift-alt-s           = 'layout v_accordion'
ctrl-shift-alt-w           = 'layout h_accordion'
ctrl-shift-alt-e           = 'layout tiles horizontal vertical'
ctrl-alt-shift-space = 'layout floating tiling'

# Other useful commands
alt-shift-c = 'reload-config'
ctrl-alt-r       = 'mode resize'

###############################################################################
# Resize Mode Key Bindings (vim-style)
[mode.resize.binding]
left = 'resize width -50'
up = 'resize height +50'
down = 'resize height -50'
right = 'resize width +50'
enter = 'mode main'
esc   = 'mode main'
